### ISSUE TITLE
figma faktid

### ISSUE THREAD

**Issue by sander-aleks** [sander-aleks/KAK100Portfolio#3]
Faktid Ametikooli kohta

**Comment by Beeak** [comment]
Kool loodi 6. novembril 1922.

Kooli algne nimi oli Ehitusinstruktorite Kool.

Kuressaare Ametikool oli esimene kutseharidus kool Saaremaal.

Esmakordselt võeti vastu 19 õpilast.

Tänapäeval õpib koolis ligi 800 õpilast.

Kokku on valikus 32 eriala.

Kooli moto on "Sinu sõber elukestvas õppes.".

Kooli visiooni järgi on KAK uuendusmeelne hariduskeskus.

Kooli logol on kujutatud kahe inimkuju stiliseeritud käepigistust.

Kooli logo autor on Madis Vaher kes on ametikoolis disaini õppesuunas õpetaja ning kunstilise kujunduse erialal õppinud.

Lisaks ametikoolile on ametikoolil eraldi sümboolikaga brändideks veel disainimajaks, tehnoloogiamajakas, hotell Mardi ja koolitusmajakas.

Ametikooli põhilised värvid on oranž ning sinine. Neeme Ranna sõnul väljendab oranž noortepärasust ja sinine nii Saaremaad ümbritsevat merd kui ka kooli järjest kasvavat sihtrühma ehk täiskasvanud õppijaid.

Ametikooli 100. sünnipäeva juubeliaastal kasutatakse juubelilogo, mille autor on kujundusgraafiku eriala õpilane Kelli Kütt.

Ametikooli laul "Meistriks ei sünnita" valmistati 2007. a kooli 85. sünnipäevaks.

Kooli põhiväärtused on koostöö, uuendusmeelsus, hoolivus ja paindlikkus.

1998. a liideti Ametikool 1992 Upal alustanud Saaremaa Kutseõppekeskusega.

Kooli nimi inglise keeles on Kuressaare Regional Training Centre.
