### ISSUE TITLE
Kooli õpetajate kontaktid (10tk)

### ISSUE THREAD

**Issue by 4avik** [sander-aleks/KAK100Portfolio#6]
Otsi vabalt kooli töötajate kontaktid kontaktid ( 10 töötajat).

[Link](https://ametikool.ee/et/kontakt)

**Comment by KevinKangur** [comment]
Neeme Rand (direktor) - 452 4611 - 505 8271 - neeme.rand@ametikool.ee

Koidu Põld (õppesekretär) - 452 4608 - koidu.pold@ametikool.ee

Piia Prei (sotsiaalpedagoog) - 452 4658 - 5919 5818 -  piia.prei@ametikool.ee

Jane Mägi (IT- ja ettevõtluse õppesuuna juhtõpetaja) - 452 4620 - 506 8383 - jane.magi@ametikool.ee

Karl Gregor Rauniste (kutseõpetaja) - 452 4651 - karl_gregor.rauniste@ametikool.ee

Toomas Kivi (kutseõpetaja) - 452 4649 - toomas.kivi@ametikool.ee

Piret Pruul (administraator) - 452 4633 - piret.pruul@ametikool.ee

Aivar Saart (tehniliste süsteemide spetsialist) - 452 4600 - 514 6956 - aivar.saart@ametikool.ee

Martti Tomson (CNC-töötlemiskeskuse operaator) - 452 4660 - martti.tomson@ametikool.ee

Erik Laes (IT-spetsialist) - 452 4668 - 5693 4580 - erik.laes@ametikool.ee
